### PR TITLE
Option to hide tabs

### PR DESCRIPTION
**Pull request by ghost**
For those who don't like tab gardening, this small collection of changes hides tabs. To use it, modify your init.lua with:

> config.show_tabs = false

### CODE REVIEW

**Comment by francesco-st** [comment]
Cool, I will probably add this into [lite-xl](https://github.com/franko/lite-xl).

Rxi will probably accept your request, I guess, but lately he is not very active on github so you may have to patient a little bit.

Otherwise I was thinking to add also a command: `core:toggle-tabs` to toggle their visibility using a command. This is somewhat overlapping with the config setting but should be ok. The config gives the default behavior and you can change at any moment with the command.

**Comment by ghost** [comment]
I'm actually not sure my approach is the best one -- it would be more in keeping with the lite philosophy to put this in a plugin. However doing that will require being able to access Node, which currently is not exported.

**Comment by ghost** [comment]
Going to close this out and instead offer a simpler PR that just refactors Node out of rootview.lua and into node.lua.

**Comment by rajhlinux** [comment]
How to hide the side panel?

**Pull request closed without merging**
