### PR TITLE
Added Auto-Save

### PR DESCRIPTION
**Pull request by WittySmirk**
Due to an issue, I saw multiple people requested auto-save so I went ahead and added it into the main program. (I figured it would be easiest this way as I had issues making this feature a plugin because it would save before you actually made the change to the document).

I hope this helps, let me know if there are any conflicts to this 👍

### CODE REVIEW

**Comment by AqilCont** [comment]
Hm, instead of every character/edit, is there a way for you to do it every second/variable time interval after the last edit, and on app close? I think it would be a bit better than calling a command and putting if statements everywhere. This method is from VSC, and I think it's pretty suitable for lite, plus a tiny bit more customizable and efficient. The current solution could also maybe get laggy for big files, if that's a concern.

**Comment by WittySmirk** [comment]
In that case I could easily make this into a plug-in instead. I thought that making it every character update could be useful, especially for having to compile continuously, but I guess the plug-in could let you find tune your cool-down and such

**Comment by AqilCont** [comment]
Ohh yeah a plugin would be better, might still require modifications to the core module(detecting last edit) but it would be a lot less intrusive and more customizable! If it's possible, I would love for it to happen :D

**Comment by AqilCont** [comment]
Will there be any progress on this in the future? Sorry for bothering you, I just wanted this feature to be properly implemented someday :D

**Comment by WittySmirk** [comment]
There definitely will be progress made in the future (I've been really busy recently) but all I need to do is make a simple sleep function and call the doc-save command after it. It should only take one coding session but I'm really busy so it will probably be out this weekend. I'm going to keep this PR open just so I can update you when I make a PR to the lite-plugins repo

**Comment by AqilCont** [comment]
Oh, wait did you make the plugin...?

**Pull request closed without merging**
