### PR TITLE
darkwood color theme

### PR DESCRIPTION
**Pull request by monolifed**

### CODE REVIEW

**Comment by lemon-sherbet** [comment]
i think this should go in https://github.com/rxi/lite-plugins

**Comment by monolifed** [comment]
Probably. It doesn't add any functionality though, it is just a theme.

**Comment by rxi** [comment]
Thanks for the PR! I'll leave a comment once I've established a place for color themes to live, as I won't be accepting new color themes into the core editor. Something similar to the `lite-plugins` repo feels like it would make sense.

**Comment by rxi** [comment]
Added the [lite-colors](https://github.com/rxi/lite-colors) repo for color themes to live in.

**Pull request closed without merging**
