### PR TITLE
Add more C++ file extensions for syntax highlighting

### PR DESCRIPTION
**Pull request by zlianon**

### CODE REVIEW

**Comment by rxi** [comment]
`%.c++$` needs to be escaped as `%.c%+%+$`, otherwise looks good!

**Comment by zlianon** [comment]
> `%.c++$` needs to be escaped as `%.c%+%+$`, otherwise looks good!

Fixed!

**Comment by rxi** [comment]
whoops -- I wasn't paying attention unfortunately and thought this was a pull request for a different file. The `language_c` file intentionally only operates on non-c++ files. I'd be happy to merge the pull request if made for the `language_cpp` file on the [plugins repository](https://github.com/rxi/lite-plugins)! Sorry about that

**Comment by heatherkovich69** [comment]
﻿

**Pull request closed without merging**
