### PR TITLE
Improve movement through words

### PR DESCRIPTION
**Pull request by dacap**
We skip all the white space if we are not in a word and go to the beginning of the word (w/previous_word_boundary) or the end of the word (w/next_word_boundary).

E.g. Current behavior on each `doc:move-to-previous-word-boundary`:
```
this   is   some  text
                    ^
this   is   some  text
                  ^
this   is   some  text
                ^
this   is   some  text
            ^
this   is   some  text
         ^
this   is   some  text
       ^
this   is   some  text
    ^
````
New behavior:
```
this   is   some  text
                    ^
this   is   some  text
                  ^
this   is   some  text
            ^
this   is   some  text
       ^
this   is   some  text
^
````

Same for `doc:move-to-next-word-boundary`

### CODE REVIEW

**Comment by JesseRMeyer** [comment]
With these changes, the space between var and the arithmetic is skipped.  I would prefer the skip to end at the next white space in the sequence, accounting for numerical symbols.

```var /= 2;```

**Comment by dacap** [comment]
You're right, I think there is another problem here. In `master` branch `doc:move-to-next-word-boundary` works in this way:
```
  var /= 2
  ^
  var /= 2
     ^
  var /= 2
      ^
  var /= 2
       ^
  var /= 2
        ^
  var /= 2
         ^
  var /= 2
          ^
```
And this is how VSCode jumps between "words":
```
var+=2
^
var+=2
   ^
var+=2
     ^
var+=2
     ^
var+=2
      ^
```
So `+=` is like another word, but `var+=2` is not one word, but 3 words. So I guess `config.non_word_chars` could be split in two tablets: `config.whitespace_chars` and `config.ops_chars` (or something like that) and the first to do when going forward/backward for a word is skipping all whitespace_chars, and then, after we find the first char (a ops_chars or a word_chars), skip all those kind characters (only ops_chars or only word_chars). It's like there are three categories:

1. whitespace (`  \t\n`)
2. operators (`+-=/*`, etc.)
3. words (`[a-z0-9]`, unicode chars, etc.)

Not sure where `"` should be. I'll be testing other possibilities, and modifying this PR in the near future if it's possible.

**Comment by dacap** [comment]
@JesseRMeyer I've added a [new commit](https://github.com/rxi/lite/pull/115/commits/1f882b57ff1c8c137b532e8d4b690b9fff2840cf) to this PR to fix the issue you've found, you can check it.

(The missing part are the `translate.start_of_word`/`translate.end_of_word` functions, which are used in Doc: Move to Start/End of Word.)

**Comment by JesseRMeyer** [comment]
Feels very natural.  Nice, quick work!  Now I'm wondering about movement through groups of vertical lines of code separated by a newline, but that's a separate issue.

**Comment by dacap** [comment]
Thank you! ^^ I've pushed another minor change but I'll leave this PR as it is by now. Probably the best idea would be to create other set of functions `translate.previous_word`/`translate.next_word` with these changes instead of modifying `translate.previous_word_boundary`/`translate.next_word_boundary`.

**Comment by rxi** [comment]
This pull request made me take a closer look at the `ctrl+left|right` and come to the agreement that the original behaviour could be improved -- I've pushed a commit which updates the word-movement, though it differs slightly from the implementation here. I feel it's a good balance between fewer-keystrokes and predictability while also not bringing in a distinction between non-word-characters and non-word-whitespace-characters.

**Comment by dacap** [comment]
👍  I'll close this PR and keep my functions in an extension in someway. I saw that the next/previous word behavior is different between editors when mixing operators and words, so there is no common rules between editors.

**Pull request closed without merging**
